# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group_picture', models.OneToOneField(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='home.Picture')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('grad_year', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(to='user.Group')),
                ('user_picture', models.OneToOneField(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='home.Picture')),
            ],
        ),
    ]
