# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 22:15
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('grad_year', models.IntegerField(default=0)),
                ('user_picture', models.ImageField(default='c:\\Git\\machine-learning-capstone\\django\\Website\\Website\\z_Media\\users\\default.jpg', max_length=300, storage=django.core.files.storage.FileSystemStorage(location='c:\\Git\\machine-learning-capstone\\django\\Website\\Website\\z_Media\\users\\'), upload_to='')),
                ('groups', models.ManyToManyField(to='user.Group')),
            ],
        ),
    ]
