# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_picture',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to='home.Picture'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_picture',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='home.Picture'),
        ),
    ]
