# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170309_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_picture',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_picture',
            field=models.ImageField(upload_to='Images/'),
        ),
    ]
