# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20170322_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_picture',
            field=models.ImageField(default='Images/default_user.jpg', upload_to='Images/'),
        ),
    ]
