# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 18:09
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20170504_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(to='user.Group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_picture',
            field=models.ImageField(default='e:\\Git\\machine-learning-capstone\\django\\Website\\Website\\z_Media\\users\\default.jpg', max_length=300, storage=django.core.files.storage.FileSystemStorage(location='e:\\Git\\machine-learning-capstone\\django\\Website\\Website\\z_Media\\users\\'), upload_to=''),
        ),
    ]
