# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20170505_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_picture',
            field=models.ImageField(default='\\users\\default.jpg', max_length=300, upload_to='users\\'),
        ),
    ]
