# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 03:43
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_picture',
            field=models.ImageField(default='c:\\Git\\machine-learning-capstone\\django\\Website\\Website\\z_Media\\users\\1_default.jpg', storage=django.core.files.storage.FileSystemStorage(location='c:\\Git\\machine-learning-capstone\\django\\Website\\Website\\z_Media\\users\\'), upload_to=''),
        ),
    ]
