# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_name', models.CharField(max_length=100)),
                ('challenge_description', models.TextField()),
                ('challenge_files_dir', models.CharField(max_length=500)),
                ('date_created', models.DateTimeField(verbose_name='date created')),
                ('challenge_image', models.OneToOneField(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='home.Picture')),
            ],
        ),
        migrations.CreateModel(
            name='HelpComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('date', models.DateTimeField(verbose_name='date written')),
                ('up_votes', models.IntegerField(default=0)),
                ('down_votes', models.IntegerField(default=0)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.Challenge')),
                ('pictures', models.ManyToManyField(to='home.Picture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_rate', models.DecimalField(decimal_places=3, max_digits=3)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.Challenge')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Group')),
            ],
        ),
    ]
