# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 22:15
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_name', models.CharField(max_length=100)),
                ('challenge_description', models.TextField()),
                ('challenge_files', models.FileField(default='c:\\Git\\machine-learning-capstone\\django\\Website\\Website\\z_Media\\challenges\\default.txt', max_length=300, storage=django.core.files.storage.FileSystemStorage(location='c:\\Git\\machine-learning-capstone\\django\\Website\\Website\\z_Media\\challenges\\'), upload_to='')),
                ('date_created', models.DateTimeField(verbose_name='date created')),
                ('challenge_image', models.ImageField(default='c:\\Git\\machine-learning-capstone\\django\\Website\\Website\\z_Media\\challenges\\challenge_avis\\default.jpg', max_length=300, storage=django.core.files.storage.FileSystemStorage(location='c:\\Git\\machine-learning-capstone\\django\\Website\\Website\\z_Media\\challenges\\challenge_avis\\'), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='HelpComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('date', models.DateTimeField(verbose_name='date written')),
                ('up_votes', models.IntegerField(default=0)),
                ('down_votes', models.IntegerField(default=0)),
                ('challenge', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='challenge.Challenge')),
                ('comment_replied_to', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='challenge.HelpComment')),
                ('pictures', models.ManyToManyField(to='home.Picture')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_rate', models.DecimalField(decimal_places=3, max_digits=3)),
                ('challenge', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='challenge.Challenge')),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Group')),
            ],
        ),
    ]
