# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpcomment',
            name='comment_replied_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='challenge.HelpComment'),
        ),
    ]
