# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20170309_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpcomment',
            name='comment_replied_to',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.CASCADE, to='challenge.HelpComment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challenge_image',
            field=models.ImageField(upload_to='Challenges/'),
        ),
    ]
