# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_auto_20170322_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpcomment',
            name='comment_replied_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='challenge.HelpComment'),
        ),
    ]
