# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_auto_20170322_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpcomment',
            name='challenge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='challenge.Challenge'),
        ),
        migrations.AlterField(
            model_name='helpcomment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='challenge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='challenge.Challenge'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Group'),
        ),
    ]
