# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 03:19
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_auto_20170322_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='challenge_files_dir',
        ),
        migrations.AddField(
            model_name='challenge',
            name='challenge_files',
            field=models.FileField(default='c:\\Git\\machine-learning-capstone\\django\\Website\\Website\\z_Media\\zzz_DEFAULTS_zzz\\default.txt', storage=django.core.files.storage.FileSystemStorage(location='c:\\Git\\machine-learning-capstone\\django\\Website\\Website\\z_Media\\challenges\\'), upload_to=''),
        ),
    ]
