# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_auto_20170505_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='submission_count',
            field=models.IntegerField(default=0),
        ),
    ]
