# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 20:03
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20170505_1409'),
        ('challenge', '0007_challenge_submission_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionProcessingBuffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_files', models.FileField(default='e:\\Git\\machine-learning-capstone\\django\\Website\\Website\\z_Media\\groups\\default.txt', max_length=300, storage=django.core.files.storage.FileSystemStorage(location='e:\\Git\\machine-learning-capstone\\django\\Website\\Website\\z_Media\\\\groups\\'), upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='code_files',
            field=models.FileField(blank=True, max_length=300, null=True, storage=django.core.files.storage.FileSystemStorage(location='e:\\Git\\machine-learning-capstone\\django\\Website\\Website\\z_Media\\\\groups\\'), upload_to=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User'),
        ),
        migrations.AddField(
            model_name='submissionprocessingbuffer',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.Submission'),
        ),
    ]
