# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0008_auto_20170505_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='code_required',
            field=models.BooleanField(default=False),
        ),
    ]
