# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 04:36
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0010_auto_20170505_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='challenge_files',
            field=models.FileField(default='\\default.zip', max_length=300, storage=django.core.files.storage.FileSystemStorage(location='e:\\Git\\machine-learning-capstone\\django\\Website\\Website\\z_Media\\challenges\\'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challenge_image',
            field=models.ImageField(default='\\default.jpg', max_length=300, storage=django.core.files.storage.FileSystemStorage(location='e:\\Git\\machine-learning-capstone\\django\\Website\\Website\\z_Media\\challenges\\challenge_avis\\'), upload_to=''),
        ),
    ]
