# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0011_auto_20170506_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='challenge_files',
            field=models.FileField(default='\\challenges\\default.zip', max_length=300, upload_to='challenges\\'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challenge_image',
            field=models.ImageField(default='\\challenges\\challenge_avis\\default.jpg', max_length=300, upload_to='challenges\\challenge_avis\\'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='code_files',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='groups\\'),
        ),
        migrations.AlterField(
            model_name='submissionprocessingbuffer',
            name='submission_files',
            field=models.FileField(default='\\groups\\default.txt', max_length=300, upload_to='groups\\'),
        ),
    ]
