# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0012_auto_20170507_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionprocessingbuffer',
            name='group',
        ),
        migrations.AlterField(
            model_name='submission',
            name='error_rate',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
        migrations.DeleteModel(
            name='SubmissionProcessingBuffer',
        ),
    ]
