# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20170322_1613'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='path',
        ),
        migrations.AddField(
            model_name='picture',
            name='pic',
            field=models.ImageField(default='-1', upload_to='Images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='user',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.CASCADE, to='user.User'),
            preserve_default=False,
        ),
    ]
