# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 06:24
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170407_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='pic',
            field=models.ImageField(default='c:\\Git\\machine-learning-capstone\\django\\Website\\Website\\z_Media\\images\\default.jpg', storage=django.core.files.storage.FileSystemStorage(location='c:\\Git\\machine-learning-capstone\\django\\Website\\Website\\z_Media\\test_images\\'), upload_to=''),
        ),
    ]
